const {chromium}=require('playwright');
const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||undefined,headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});let errors=[];page.on('pageerror',e=>errors.push(e.message));const result=[];
const check=async(name,fn)=>{await fn();result.push({test:name,status:'PASS'})};
const click=async(a)=>page.locator(`[data-action="${a}"]`).first().click();
fs.mkdirSync(root+'/evidence',{recursive:true});
const shot=async(name)=>{await page.evaluate(()=>{document.querySelector('#toast').style.display='none';window.scrollTo(0,0)});await page.screenshot({path:root+'/evidence/'+name+'.png',fullPage:false})};
await page.goto('file://'+root+'/prototype/index.html');await shot('welcome');
await check('Onboarding validates age, nickname and interests',async()=>{await click('start');await click('setup-next');assert((await page.locator('#setup-error').innerText()).includes('confirm'));await page.locator('#adult').check();await click('setup-next')});
await shot('consent');
await check('Discovery requires opt-in',async()=>{await click('join');assert((await page.locator('#consent-error').innerText()).includes('Choose'));await click('skip');assert(await page.getByText('You are hidden',{exact:true}).isVisible());await click('toggle-visible');await click('enable')});
await shot('discovery');
await check('Interest filter excludes nonmatching profiles',async()=>{await page.locator('[data-filter="Photography"]').click();assert.equal(await page.locator('[data-person]').count(),2);await page.locator('[data-filter="All"]').click()});
await page.locator('[data-person="maple"]').click();await shot('profile');
await check('Request waits for recipient consent',async()=>{await click('request');assert.equal(await page.locator('#message').count(),0);assert(await page.getByText('Request sent · waiting',{exact:true}).isVisible())});await shot('request');
await check('Decline opens no chat',async()=>{await click('decline');await page.locator('[data-go="chats"]').click();assert(await page.getByText('Your next hello is nearby.').isVisible());await page.locator('[data-go="nearby"]').click();await page.locator('[data-person="maple"]').click();await click('request')});
await check('Accepted request opens anonymous chat',async()=>{await click('accept');assert(await page.locator('#message').isVisible());assert.equal(await page.getByRole('heading',{name:'Alex',exact:true}).count(),0)});await shot('chat');
await check('Blank messages rejected; input rendered as text',async()=>{const n=await page.locator('.bubble').count();await page.locator('#message').fill('  ');await page.locator('#message-form button').click();assert.equal(await page.locator('.bubble').count(),n);await page.locator('#message').fill('<img src=x onerror=alert(1)>');await page.locator('#message-form button').click();assert.equal(await page.locator('.thread img').count(),0);assert((await page.locator('.bubble.mine').innerText()).includes('<img'));await page.evaluate(()=>state.conversations.maple.messages.splice(-2));await page.locator('#message').fill('A campus photo walk sounds great!');await page.locator('#message-form button').click()});
await check('Reveal dialog cancel leaves identity hidden',async()=>{await click('reveal');await click('close');assert(await page.getByText('Anonymous connection',{exact:true}).isVisible())});
await click('reveal');await shot('reveal-dialog');
await check('First consent does not reveal identities',async()=>{await click('reveal-confirm');assert.equal(await page.getByRole('heading',{name:'Alex',exact:true}).count(),0);assert(await page.getByText('You agreed to reveal. Waiting for the other person. Identity is still hidden.').isVisible())});await shot('reveal-waiting');
await check('Reveal decline and withdrawal retain anonymity',async()=>{await click('reveal-decline');await click('reveal');await click('reveal-confirm');await click('withdraw');assert(await page.getByText('Anonymous connection',{exact:true}).isVisible());await click('reveal');await click('reveal-confirm')});
await check('Mutual consent reveals fictional names',async()=>{await click('agree');assert(await page.getByRole('heading',{name:'Alex',exact:true}).isVisible());assert(await page.getByText('You both chose to reveal').isVisible())});await shot('revealed');
await check('Area departure starts 48-hour timer and hides discovery',async()=>{await click('leave');assert((await page.locator('.notice').innerText()).includes('48 hours'));assert.equal(await page.evaluate(()=>state.visible),false)});await shot('timer');
await check('Expiry clears messages and consent',async()=>{await click('advance');assert((await page.locator('h1').innerText()).includes('has closed.'));assert.equal(await page.locator('#message').count(),0);assert.equal(await page.evaluate(()=>state.conversations.maple.messages.length),0);assert.equal(await page.evaluate(()=>state.conversations.maple.reveal),'none')});await shot('expired');
await click('discover');await click('toggle-visible');await click('enable');await page.locator('[data-person="sunny"]').click();await click('request');await click('accept');await click('safety');await click('report');await shot('report');
await check('Report logs locally and block removes connection',async()=>{await click('report-confirm');assert(await page.getByRole('heading',{name:'Demo report log · 1'}).isVisible());assert(await page.getByRole('heading',{name:'Blocked profiles · 1'}).isVisible());assert.equal(await page.evaluate(()=>state.conversations.sunny),undefined)});await shot('privacy');
await check('Unblock does not resurrect deleted messages',async()=>{await page.locator('[data-unblock="sunny"]').click();assert.equal(await page.evaluate(()=>state.conversations.sunny),undefined)});
await check('Profile edit validates two interests',async()=>{await click('edit');await page.locator('[data-edit-interest="Coffee"]').click();await click('edit-done');assert((await page.locator('#edit-error').innerText()).includes('two'));await page.locator('[data-edit-interest="Coffee"]').click();await click('edit-done')});
await check('Escape cancels incomplete interest changes',async()=>{await click('edit');await page.locator('[data-edit-interest="Coffee"]').click();await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>state.interests.length),2)});
await check('Dialog keeps keyboard focus inside',async()=>{await click('reset');for(let i=0;i<5;i++){await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)))}await page.keyboard.press('Escape')});
await check('Reset cancellation preserves session',async()=>{await click('reset');await click('close');assert(await page.getByRole('heading',{name:'Demo report log · 1'}).isVisible())});
await check('Reset clears session',async()=>{await click('reset');await click('reset-confirm');await page.waitForLoadState();assert(await page.getByRole('heading',{name:'Good people.Common ground.'}).count()||await page.locator('[data-action="start"]').isVisible())});
await check('Mobile viewport has no horizontal overflow',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))});
await check('Narrow 320px viewport has no horizontal overflow',async()=>{await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))});
await page.setViewportSize({width:1440,height:1000});await shot('desktop');
await check('Desktop viewport has no horizontal overflow',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))});
await check('No JavaScript runtime errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(root+'/evidence/test-results.json',JSON.stringify({date:new Date().toISOString(),browser:'Brave Chromium via Playwright',tests:result},null,2));
console.log(JSON.stringify({count:result.length,results:result},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

